image: Visual Studio 2017
version: 1.3.3-rc-{build}
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
build_script:
- ps: >-
    cd C:\projects\xgain

    .\Scripts\build.ps1 -version $env:appveyor_build_number

    .\scripts\pack.ps1 -version $env:appveyor_build_number
test_script:
- ps: >-
    $coverageFile = "coverage.xml"


    # run tests

    .\Scripts\runTests.ps1 -fileName $coverageFile


    # add python folder into Path variable

    $env:Path = $env:Path + "C:\\Python34;C:\\Python34\\Scripts;"


    # install codecov plugin

    pip install codecov


    # send code coverage to the codecov server

    codecov -f $coverageFile -X gcov
artifacts:
- path: '**\*.nupkg'
  name: NuGet package